# Generated by Django 4.1 on 2022-09-07 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priority', models.CharField(blank=True, choices=[('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('PE', 'Pending'), ('IN', 'In Progress'), ('CM', 'Complete')], max_length=20)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('assignee', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('user_story', models.TextField(blank=True)),
                ('sprint', models.IntegerField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
