# Generated by Django 4.1 on 2022-09-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
