# Generated by Django 4.1 on 2022-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
