# Generated by Django 4.1.1 on 2022-09-30 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('sprint_goal', models.TextField()),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('IN', 'Ongoing'), ('CM', 'Ended')], default='PE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sprint_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
