# Generated by Django 4.1 on 2022-09-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(max_length=50, verbose_name='<django.db.models.fields.CharField>.<django.db.models.fields.CharField>@company.com'),
        ),
    ]
