# Generated by Django 4.1 on 2022-09-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
