# Generated by Django 4.1 on 2022-09-27 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sprint_name", models.CharField(max_length=100)),
                ("sprint_goal", models.CharField(max_length=250)),
                (
                    "task",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("T1", "Task 1"),
                            ("T2", "Task 2"),
                            ("T3", "Task 3"),
                            ("T4", "Task 4"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assignee", models.CharField(max_length=100)),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1W", "1 Week"),
                            ("2W", "2 Weeks"),
                            ("3W", "3 Weeks"),
                            ("4W", "4 Weeks"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
