# Generated by Django 4.1 on 2022-09-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createSprintApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="is_sprint_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="sprint_goal",
            field=models.CharField(max_length=250, verbose_name="Sprint Goal"),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="sprint_name",
            field=models.CharField(max_length=100, verbose_name="Sprint Name"),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
