# Generated by Django 4.1 on 2022-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createSprintApp", "0003_rename_created_date_sprint_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="sprint_Goal",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="sprint_Name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
