# Generated by Django 4.1 on 2022-09-29 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createSprintApp", "0004_alter_sprint_sprint_goal_alter_sprint_sprint_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="sprint_Name",
            field=models.CharField(
                default="",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator("[+-/%]", inverse_match=True)
                ],
            ),
        ),
    ]
