# Generated by Django 4.1 on 2022-09-29 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createSprintApp", "0005_alter_sprint_sprint_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sprint", old_name="created_Date", new_name="created_date",
        ),
        migrations.RenameField(
            model_name="sprint", old_name="sprint_Goal", new_name="sprint_goal",
        ),
        migrations.RemoveField(model_name="sprint", name="end_Date",),
        migrations.RemoveField(model_name="sprint", name="is_Sprint_Complete",),
        migrations.RemoveField(model_name="sprint", name="sprint_Name",),
        migrations.RemoveField(model_name="sprint", name="start_Date",),
        migrations.AlterField(
            model_name="sprint",
            name="assignee",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sprint",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sprint",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 9, 29, 12, 28, 29, 822020, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
