# Generated by Django 4.1 on 2022-09-29 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("createSprintApp", "0006_rename_created_date_sprint_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 9, 29, 12, 34, 2, 780162, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
