# Generated by Django 4.1 on 2022-09-29 12:35

import datetime
from django.db import migrations, models
from django.utils.datetime_safe import date


class Migration(migrations.Migration):

    dependencies = [
        ("createSprintApp", "0007_alter_sprint_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="start_date",
            field=models.DateField(default=date(2022, 9, 29)),
        ),
    ]
