# Generated by Django 4.1 on 2022-09-29 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("createSprintApp", "0008_alter_sprint_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
